SELECT PURCHASES.USER_ID as USER_ID, count(*) as PURCHASE_COUNT, sum(CHARACTERS.PRICE) as TOTAL_PRICE
from GAME_USERS,PURCHASES,CHARACTERS
where GAME_USERS.ID = PURCHASES.USER_ID and PURCHASES.ITEM = CHARACTERS.NAME
group by PURCHASES.US
ER_ID